<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>packshrink</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.1.0" />
    <PackageReference Include="Microsoft.Toolkit.HighPerformance" Version="7.1.2" />
    <ProjectReference Include="..\..\..\codewalker\CodeWalker-fork\CodeWalker.Core\CodeWalker.Core.csproj" />
  </ItemGroup>

</Project>
